### ISSUE TITLE
Single or multiple instances of PyCSW

### ISSUE THREAD

**Issue by jvanulde** [federal-geospatial-platform/fgp-metadata-proxy#17]
Determine if we need multiple instances of PyCSW, one for each target (e.g. BC, Alberta, EODMS, etc.).

**Comment by keballantyne** [comment]
A PyCSW instance for each target will be required.

**Comment by jvanulde** [comment]
Alright. I would work on that next Sprint (#6) so I would reassign it to that milestone.
