### ISSUE TITLE
User Story: Lower barrier to entry

### ISSUE THREAD

**Issue by jvanulde** [federal-geospatial-platform/fgp-metadata-proxy#9]
As a project lead,
I would like to have the barrier to entry for the FGP lowered to the extent possible,
So that we can onboard additional partners with minimal effort on their end.

**Comment by CindyMitchell** [comment]
Agreed - especially with third-party impact assessment/environmental assessment for cumulative effects portal coming to FGP. Can we explore S3 metadata lake option for non-federal data?

**Comment by jvanulde** [comment]
@CindyMitchell we should think about it. Can you add a User Story for this and put it in the Parking Lot? That way its documented and we can address it if we have time.
